# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-ohai")
  raise "vagrant-ohai plugin is not installed! Install with 'vagrant plugin install vagrant-ohai'"
end

NODE_SCRIPT = <<EOF.freeze
  wget https://packages.chef.io/files/stable/chef-workstation/21.2.278/ubuntu/20.04/chef-workstation_21.2.278-1_amd64.deb
  dpkg -i chef-workstation_21.2.278-1_amd64.deb
EOF

def set_hostname(server)
  server.vm.provision 'shell', inline: "hostname #{server.vm.hostname}"
end

Vagrant.configure(2) do |config|
  config.vm.define 'ubuntu-20-04' do |n|
    n.vm.box = 'bento/ubuntu-20.04'
    # n.vm.box_url = 'https://vagrantcloud.com/bento/boxes/centos-7.2'
    # n.vm.box_version = '2.3.1'
    n.vm.hostname = 'ubuntu-20-04'
    n.vm.provision :shell, inline: NODE_SCRIPT.dup
    set_hostname(n)
  end
end
